# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\test_student_apply.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.test_login_test import TestCaseTestLogin as TestLogin


class TestCaseTestStudentApply(HttpRunner):

    config = Config("学员报名").base_url("http://10.168.6.3:6222")

    teststeps = [
        Step(RunTestCase("登录").with_variables(**{}).call(TestLogin)),
        Step(
            RunRequest("已报名学员报名提交")
            .with_variables(**{"up_data": "${get_xml_body(testcases/已报名学员.xml)}"})
            .post("/EmpMgr/Ajax2Servlet")
            .with_params(**{"style": "new", "tier": "business"})
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=GBK",
                    "DNT": "1",
                    "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
                }
            )
            .with_data("$up_data")
            .teardown_hook("${teardown_hook_xml_json($response)}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/xml;charset=UTF-8")
            .assert_equal("body.output.head.retCode", "-1")
            .assert_equal(
                "body.output.head.retDesc", "该学员已报名了[经营性道路旅客运输驾驶员]在经纬机动车驾驶员培训学校，未通过考试"
            )
        ),
        Step(
            RunRequest("新学员报名提交")
            .with_variables(**{"up_data": "${get_xml_body(testcases/新学员报名.xml)}"})
            .post("/EmpMgr/Ajax2Servlet")
            .with_params(**{"style": "new", "tier": "business"})
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=GBK",
                    "DNT": "1",
                    "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
                }
            )
            .with_data("$up_data")
            .teardown_hook("${teardown_hook_xml_json($response)}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/xml;charset=UTF-8")
            .assert_equal("body.output.head.retCode", "0")
            .assert_equal("body.output.head.retDesc", "报名成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseTestStudentApply().test_start()
