# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\test_login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").base_url("http://10.168.6.3:6222")

    teststeps = [
        Step(
            RunRequest("/EmpMgr/twoevslogin")
            .post("/EmpMgr/twoevslogin")
            .with_params(
                **{"PASSWRD": "ctop123", "RAND": "72", "TYPE": "1", "USERCODE": "ld001"}
            )
            .with_headers(
                **{
                    "DNT": "1",
                    "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
                    "x-requested-with": "XMLHttpRequest",
                }
            )
            .with_data("")
            .teardown_hook("${teardown_hook_xml_json($response)}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/xml;charset=UTF-8")
            .assert_equal("body.output.head.retCode", "0")
            .assert_equal("body.output.head.retDesc", "操作成功")
            .assert_equal("body.output.head.retValue", "/twoevslogin")
        ),
        Step(
            RunRequest("/EmpMgr/mainsv")
            .post("/EmpMgr/mainsv")
            .with_params(
                **{
                    "CUSTOMERID": "G0001",
                    "PASSWRD": "ctop123",
                    "USERCODE": "ld001",
                    "height": "768",
                    "rand": "72",
                    "width": "1366",
                }
            )
            .with_headers(
                **{
                    "DNT": "1",
                    "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
                    "x-requested-with": "XMLHttpRequest",
                }
            )
            .with_data("")
            .teardown_hook("${teardown_hook_xml_json($response)}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/xml;charset=UTF-8")
            .assert_equal("body.output.head.retCode", "0")
            .assert_equal("body.output.head.retDesc", "操作成功")
            .assert_equal("body.output.head.retValue", "/mainsv")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
