# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\qryUserRefDetail.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login1_test import TestCaseLogin1 as Login1


class TestCaseQryuserrefdetail(HttpRunner):

    config = Config("查询用户关联信息").base_url("http://10.168.1.180")

    teststeps = [
        Step(
            RunTestCase("登录系统")
            .call(Login1)
            .export(*["userName", "userCode", "authToken"])
        ),
        Step(
            RunRequest("查询用户关联信息")
            .get("/serv/sysrest/sys/user/qryUserRefDetail")
            .with_params(**{"data": '{"userCode":"$userCode"}', "t": "1652930207"})
            .with_headers(
                **{
                    "Authorization": "Bearer $authToken",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "agentUser": "$userCode",
                    "agentUserName": "${string_encode($userName)}",
                    "opUser": "$userCode",
                    "opUserName": "${string_encode($userName)}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 1)
            .assert_equal("body.desc", "success")
            .assert_equal("body.data.userInfo.userCode", "$userCode")
        ),
    ]


if __name__ == "__main__":
    TestCaseQryuserrefdetail().test_start()
