# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\getflow.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login1_test import TestCaseLogin1 as Login1


class TestCaseGetflow(HttpRunner):

    config = Config("获取工作流").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunTestCase("登录系统")
            .with_variables(**{})
            .call(Login1)
            .export(*["user_code", "auth_token"])
        ),
        Step(
            RunRequest("/hncb/api/flflow/qryFlowByCondition")
            .get("/hncb/api/flflow/qryFlowByCondition")
            .with_params(
                **{
                    "data": '{"startdate":"2022-01-01","enddate":"2022-12-31","userid":"20200610102606808_1B4324D9A89B4CDEB0BAC2044CC674B5","categorycode":"430205"}',
                    "t": "1652944329",
                }
            )
            .with_headers(
                **{
                    "Authorization": "Bearer $auth_token",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "dbSchema": "county430205",
                    "opUser": "$user_code",
                    "partitionCode": "P1_SERVICE",
                    "serviceCheckCode": "df36919186eefc8e6a29005a2367c984",
                    "tenantId": "430205",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain;charset=UTF-8")
            .assert_equal("body.code", 1)
            .assert_equal("body.desc", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetflow().test_start()
