# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\login1.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin1(HttpRunner):

    config = (
        Config("财补系统登录")
        .variables(**{"user_code": "jjj430205001", "password": "abc123"})
        .base_url("${ENV(BASE_URL)}")
        .export(*["auth_token", "user_code"])
    )

    teststeps = [
        Step(
            RunRequest("获取验证码")
            .get("/hncb/sys/encrypt/verifyCode")
            .with_params(**{"_": "1652844797524"})
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .extract()
            .with_jmespath("body.data.code", "verify_code")
            .with_jmespath("body.data.key", "verify_key")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain;charset=UTF-8")
        ),
        Step(
            RunRequest("获取公钥")
            .get("/hncb/sys/encrypt/rsaPublicKey")
            .with_params(**{"_": "1652844797525"})
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                    "opUser": "null",
                }
            )
            .extract()
            .with_jmespath("body.data.key", "publickey")
            .with_jmespath("body.data.rsaKeyMod", "rsakeymod")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain;charset=UTF-8")
        ),
        Step(
            RunRequest("系统登录")
            .get("/hncb/sys/user/login")
            .with_params(
                **{
                    "_": "1652844797526",
                    "data": '{"userCode":"$user_code","passwd":"${rsa_passwd($password, $rsakeymod)}","key":"$publickey","verifyCode":"$verify_code","verifyKey":"$verify_key","original_jsp":"","signed_data":"","errorcode":"","errormsg":""}',
                }
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .extract()
            .with_jmespath("body.data.authToken", "auth_token")
            .with_jmespath("body.data.userCode", "user_code")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain;charset=UTF-8")
            .assert_equal("body.code", 1)
            .assert_equal("body.data.userCode", "$user_code")
            .assert_equal("body.desc", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin1().test_start()
