# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\qryUserRefDetail.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login1_test import TestCaseLogin1 as Login1


class TestCaseQryuserrefdetail(HttpRunner):

    config = Config("查询用户关联信息").base_url("http://10.168.6.127:30005")

    teststeps = [
        Step(
            RunTestCase("登录系统")
            .with_variables(**{})
            .call(Login1)
            .export(*["auth_token", "user_code"])
        ),
        Step(
            RunRequest("查询用户关联信息")
            .get("/hncb/sys/user/qryUserRefDetail")
            .with_params(**{"data": '{"userCode":"$user_code"}', "t": "1652844803"})
            .with_headers(
                **{
                    "Authorization": "Bearer $auth_token",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "opUser": "$user_code",
                    "serviceCheckCode": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain;charset=UTF-8")
            .assert_equal("body.code", 1)
            .assert_equal("body.desc", "success")
            .assert_equal("body.data.userInfo.userName", "炎陵县测试")
            .assert_equal("body.data.userInfo.userCode", "$user_code")
        ),
    ]


if __name__ == "__main__":
    TestCaseQryuserrefdetail().test_start()
